language: node_js
node_js:
  - '10'
  - '12'
  - '16'

sudo: required

before_install:
  - "npm install -g npm@latest"
install:
  - npm install
script:
  - npm run test
  
after_script:
  - npm install codecov && codecov

services:
  - mongodb
